from typing import Protocol

from domain.shared.base import Product, ProductFamily


class ProductRepositoryProtocol(Protocol):
    def save(self, product: Product) -> None: ...

    def get_by_id(self, product_id: str) -> Product | None: ...

    def get_by_sku(self, sku: str) -> Product | None: ...

    def get_by_type(self, type: ProductFamily) -> tuple[Product, ...]: ...

    def get_by_info_id(self, info_id: str) -> tuple[Product, ...]: ...

    def get_by_brand_id(self, info_id: str) -> tuple[Product, ...]: ...
