from datetime import datetime
from typing import Protocol

from domain.entities.settings import SystemSettings


class SystemSettingsRepositoryProtocol(Protocol):
    def save(self, settings: SystemSettings) -> None: ...
    def get_all(self) -> tuple[SystemSettings, ...]: ...
    def get_all_from_date(self, date: datetime) -> tuple[SystemSettings, ...]: ...
    def get_current_setting(self) -> SystemSettings: ...
    def get_by_id(self, settings_id: str) -> SystemSettings: ...
